[package]
name = "fileorg"
version = "0.1.0"
edition = "2021"
authors = ["Infernum <infernum1212@gmail.com>"]
description = "A simple File Organizer CLI tool made in rust."
license = "MIT"
keywords = ["file", "organize"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
